### ISSUE TITLE
The game doesn't open

### ISSUE THREAD

**Issue by Lodnik** [GoryMoon/StreamEngineer#2]
Hello there!

First of all, i loved the idea of how this works! Unfortunately i couldn't put it to work for me, when i try put it i have the error below, the game doesn't even open, just goes on the crash report, i tried put the plugin in another drive, like C:, but the same happens, i followed the instructions on how to set up perfectly, the line of the report:

2020-02-14 13:00:44.953 - Thread:   1 ->  Exception occured: System.IO.FileLoadException: Could not load file or assembly 'file:///G:\StreamEngineer-1.18\StreamEngineer.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'file:///G:\StreamEngineer-1.18\StreamEngineer.dll' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at VRage.Plugins.MyPlugins.RegisterFromArgs(String[] args)
   at Sandbox.MySandboxGame.RegisterAssemblies(String[] args)
   at Sandbox.MySandboxGame..ctor(String[] commandlineArgs, IntPtr windowHandle)
   at SpaceEngineers.Game.SpaceEngineersGame..ctor(String[] commandlineArgs)
   at SpaceEngineers.MyProgram.Main(String[] args)

I have a friend who is a developer and the plugin worked for him, i don't have any development tools to work with, i'm just a common user, i hope this infos can help you.

**Comment by GoryMoon** [comment]
How did you download it, was it from the releases page and then extracted or did you download the .dll files separately?
You can test fixing it by using the following solution described here: https://stackoverflow.com/a/15238782

**Comment by Lodnik** [comment]
Thanks for the reply, it was the unblock option, now it opens perfectly i had downloaded through the releases pages, now i can config all and start using it.
