### ISSUE TITLE
Recieve the following error when trying to run SE with Plugin

### ISSUE THREAD

**Issue by willkillyaquick** [GoryMoon/StreamEngineer#4]
Hi,

I am attempting a new attempt in installing the plugin on Space Engineers.  I following the Instructions on the Read me and also had to unblock the .DLL files.  However, the plug in caused Space Engineers to crash.

I am using Space Engineer's version : App Version: 01_194_211

I get the following when Launching Space Engineers:

2020-05-27 06:51:38.879 - Thread:   1 ->  Exception occured: System.MissingMethodException: Method not found: 'Sandbox.Graphics.GUI.MyGuiScreenMessageBox Sandbox.Graphics.GUI.MyGuiSandbox.CreateMessageBox(Sandbox.Graphics.GUI.MyMessageBoxStyleEnum, Sandbox.Graphics.GUI.MyMessageBoxButtonsType, System.Text.StringBuilder, System.Text.StringBuilder, System.Nullable`1<VRage.Utils.MyStringId>, System.Nullable`1<VRage.Utils.MyStringId>, System.Nullable`1<VRage.Utils.MyStringId>, System.Nullable`1<VRage.Utils.MyStringId>, System.Action`1<ResultEnum>, Int32, ResultEnum, Boolean, System.Nullable`1<VRageMath.Vector2>, Boolean)'.
   at GoryMoon.StreamEngineer.Plugin.ScreenAdded(MyGuiScreenBase screenBase)
   at Sandbox.Graphics.GUI.MyScreenManager.NotifyScreenAdded(MyGuiScreenBase screen)
   at Sandbox.Graphics.GUI.MyScreenManager.AddScreens()
   at Sandbox.Graphics.GUI.MyScreenManager.Update(Int32 totalTimeInMS)
   at Sandbox.Graphics.GUI.MyDX9Gui.Update(Int32 totalTimeInMS)
   at Sandbox.Graphics.GUI.MyGuiSandbox.Update(Int32 totalTimeInMS)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)

Love the idea of Twitch interaction games.  Excited to try this out.  

Thanks,

Will

**Comment by GoryMoon** [comment]
Have built and tested [1.19](https://github.com/GoryMoon/StreamEngineer/releases/tag/1.19) against the latest SpaceEngineers version so you should try that.
