### ISSUE TITLE
Crash on World Load

### ISSUE THREAD

**Issue by RevZoeGaming** [GoryMoon/StreamEngineer#8]
I receive the following crash message when loading into any world or generating a new one: 

Exception occurred: System.MissingMethodException: Method not found: 'Void Sandbox.Graphics.MyGuiManager.DrawString(System.String, System.Text.StringBuilder, VRageMath.Vector2, Single, System.Nullable`1<VRageMath.Color>, VRage.Utils.MyGuiDrawAlignEnum, Boolean, Single)'.
   at GoryMoon.StreamEngineer.ActionNotification.Draw()
   at Sandbox.Game.World.MySession.DrawAsync()
   at Sandbox.Game.Gui.MyGuiScreenGamePlay.<>c.<LoadData>b__41_0()
   at ParallelTasks.DelegateWork.DoWork(WorkData workData)
   at ParallelTasks.WorkItem.DoWork(Int32 expectedID)
2020-12-27 12:59:38.620 - Thread:   1 ->  Exception Data:
	Exception Info: Holder ID: 36; m_runCount: 36; m_executing: 1; MaximumThreads: 1
	Work Options: MaximumThreads: 1, QueueFIFO: False, DebugName: Draw Session Components, TaskType: WorkItem
2020-12-27 12:59:38.624 - Thread:   1 ->  Task Exception Stack:
   at ParallelTasks.WorkItem.ThrowExceptionsInternal(Int32 runId)
   at ParallelTasks.Task.WaitOrExecute(Boolean blocking)
   at Sandbox.Game.Gui.MyGuiScreenGamePlay.ScreenManagerOnEndOfDraw()
   at Sandbox.Graphics.GUI.MyScreenManager.Draw()
   at Sandbox.Graphics.GUI.MyDX9Gui.Draw()
   at Sandbox.Graphics.GUI.MyGuiSandbox.Draw()
   at Sandbox.MySandboxGame.PrepareForDraw()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
2020-12-27 12:59:38.624 - Thread:   1 ->  Showing message
2020-12-27 12:59:38.991 - Thread:   1 ->

**Comment by GoryMoon** [comment]
Should be fixed in `1.22`.
Have loaded into the game and run the meteor action, can't test all actions atm.
If you find any action not working please make an issue about that.
